# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Dict

from .async_base_client import AsyncBaseClient
from .version import Version


def gql(q: str) -> str:
    return q


class Stash(AsyncBaseClient):
    async def version(self, **kwargs: Any) -> Version:
        query = gql(
            """
            query Version {
              version {
                hash
                version
                build_time
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="Version", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Version.model_validate(data)
