# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Dict, List, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .images_by_ids import ImagesByIds
from .images_by_search import ImagesBySearch
from .version import Version


def gql(q: str) -> str:
    return q


class Stash(BaseClient):
    def version(self, **kwargs: Any) -> Version:
        query = gql(
            """
            query Version {
              version {
                hash
                version
                build_time
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="Version", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Version.model_validate(data)

    def images_by_ids(
        self, ids: Union[Optional[List[str]], UnsetType] = UNSET, **kwargs: Any
    ) -> ImagesByIds:
        query = gql(
            """
            query ImagesByIds($ids: [ID!]) {
              findImages(ids: $ids, filter: {per_page: -1}) {
                images {
                  ...Img
                }
              }
            }

            fragment Img on Image {
              id
              urls
              title
              paths {
                image
                thumbnail
                preview
              }
              visual_files {
                __typename
                ... on ImageFile {
                  id
                  path
                  size
                  width
                  height
                  fingerprints {
                    type
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"ids": ids}
        response = self.execute(
            query=query, operation_name="ImagesByIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ImagesByIds.model_validate(data)

    def images_by_search(self, q: str, **kwargs: Any) -> ImagesBySearch:
        query = gql(
            """
            query ImagesBySearch($q: String!) {
              findImages(ids: [], filter: {q: $q, per_page: -1}) {
                images {
                  ...Img
                }
              }
            }

            fragment Img on Image {
              id
              urls
              title
              paths {
                image
                thumbnail
                preview
              }
              visual_files {
                __typename
                ... on ImageFile {
                  id
                  path
                  size
                  width
                  height
                  fingerprints {
                    type
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"q": q}
        response = self.execute(
            query=query, operation_name="ImagesBySearch", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ImagesBySearch.model_validate(data)
