# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class FindTagsByRegex(BaseModel):
    find_tags: "FindTagsByRegexFindTags" = Field(alias="findTags")


class FindTagsByRegexFindTags(BaseModel):
    tags: List["FindTagsByRegexFindTagsTags"]


class FindTagsByRegexFindTagsTags(BaseModel):
    id: str
    name: str


FindTagsByRegex.model_rebuild()
FindTagsByRegexFindTags.model_rebuild()
