# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import Img


class GetImagesByIds(BaseModel):
    find_images: "GetImagesByIdsFindImages" = Field(alias="findImages")


class GetImagesByIdsFindImages(BaseModel):
    images: List["GetImagesByIdsFindImagesImages"]


class GetImagesByIdsFindImagesImages(Img):
    pass


GetImagesByIds.model_rebuild()
GetImagesByIdsFindImages.model_rebuild()
