# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import Img


class ImagesByTagIds(BaseModel):
    find_images: "ImagesByTagIdsFindImages" = Field(alias="findImages")


class ImagesByTagIdsFindImages(BaseModel):
    images: List["ImagesByTagIdsFindImagesImages"]


class ImagesByTagIdsFindImagesImages(Img):
    pass


ImagesByTagIds.model_rebuild()
ImagesByTagIdsFindImages.model_rebuild()
