# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import Img


class ImagesBySearch(BaseModel):
    find_images: "ImagesBySearchFindImages" = Field(alias="findImages")


class ImagesBySearchFindImages(BaseModel):
    images: List["ImagesBySearchFindImagesImages"]


class ImagesBySearchFindImagesImages(Img):
    pass


ImagesBySearch.model_rebuild()
ImagesBySearchFindImages.model_rebuild()
