# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import Img


class ImagesByIds(BaseModel):
    find_images: "ImagesByIdsFindImages" = Field(alias="findImages")


class ImagesByIdsFindImages(BaseModel):
    images: List["ImagesByIdsFindImagesImages"]


class ImagesByIdsFindImagesImages(Img):
    pass


ImagesByIds.model_rebuild()
ImagesByIdsFindImages.model_rebuild()
