# Generated by ariadne-codegen
# Source: http://fs.local:9999/graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel, Upload
from .enums import (
    BlobsStorageType,
    BulkUpdateIdMode,
    CircumisedEnum,
    CriterionModifier,
    FilterMode,
    GenderEnum,
    HashAlgorithm,
    IdentifyFieldStrategy,
    ImageLightboxDisplayMode,
    ImageLightboxScrollMode,
    ImportDuplicateEnum,
    ImportMissingRefEnum,
    OrientationEnum,
    PreviewPreset,
    ResolutionEnum,
    SortDirectionEnum,
    StreamingResolutionEnum,
)


class AddTempDLNAIPInput(BaseModel):
    address: str
    duration: Optional[int] = None


class AnonymiseDatabaseInput(BaseModel):
    download: Optional[bool] = None


class AssignSceneFileInput(BaseModel):
    scene_id: str
    file_id: str


class AutoTagMetadataInput(BaseModel):
    paths: Optional[List[str]] = None
    performers: Optional[List[str]] = None
    studios: Optional[List[str]] = None
    tags: Optional[List[str]] = None


class BackupDatabaseInput(BaseModel):
    download: Optional[bool] = None


class BulkGalleryUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    code: Optional[str] = None
    url: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    date: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    scene_ids: Optional["BulkUpdateIds"] = None
    studio_id: Optional[str] = None
    tag_ids: Optional["BulkUpdateIds"] = None
    performer_ids: Optional["BulkUpdateIds"] = None


class BulkGroupUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    tag_ids: Optional["BulkUpdateIds"] = None
    containing_groups: Optional["BulkUpdateGroupDescriptionsInput"] = None
    sub_groups: Optional["BulkUpdateGroupDescriptionsInput"] = None


class BulkImageUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    title: Optional[str] = None
    code: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    url: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    date: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    studio_id: Optional[str] = None
    performer_ids: Optional["BulkUpdateIds"] = None
    tag_ids: Optional["BulkUpdateIds"] = None
    gallery_ids: Optional["BulkUpdateIds"] = None


class BulkMovieUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    tag_ids: Optional["BulkUpdateIds"] = None


class BulkPerformerUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    disambiguation: Optional[str] = None
    url: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    gender: Optional[GenderEnum] = None
    birthdate: Optional[str] = None
    ethnicity: Optional[str] = None
    country: Optional[str] = None
    eye_color: Optional[str] = None
    height_cm: Optional[int] = None
    measurements: Optional[str] = None
    fake_tits: Optional[str] = None
    penis_length: Optional[float] = None
    circumcised: Optional[CircumisedEnum] = None
    career_length: Optional[str] = None
    tattoos: Optional[str] = None
    piercings: Optional[str] = None
    alias_list: Optional["BulkUpdateStrings"] = None
    twitter: Optional[str] = None
    instagram: Optional[str] = None
    favorite: Optional[bool] = None
    tag_ids: Optional["BulkUpdateIds"] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    details: Optional[str] = None
    death_date: Optional[str] = None
    hair_color: Optional[str] = None
    weight: Optional[int] = None
    ignore_auto_tag: Optional[bool] = None
    custom_fields: Optional["CustomFieldsInput"] = None


class BulkSceneUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    ids: Optional[List[str]] = None
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    director: Optional[str] = None
    url: Optional[str] = None
    urls: Optional["BulkUpdateStrings"] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    studio_id: Optional[str] = None
    gallery_ids: Optional["BulkUpdateIds"] = None
    performer_ids: Optional["BulkUpdateIds"] = None
    tag_ids: Optional["BulkUpdateIds"] = None
    group_ids: Optional["BulkUpdateIds"] = None
    movie_ids: Optional["BulkUpdateIds"] = None


class BulkTagUpdateInput(BaseModel):
    ids: Optional[List[str]] = None
    description: Optional[str] = None
    aliases: Optional["BulkUpdateStrings"] = None
    ignore_auto_tag: Optional[bool] = None
    favorite: Optional[bool] = None
    parent_ids: Optional["BulkUpdateIds"] = None
    child_ids: Optional["BulkUpdateIds"] = None


class BulkUpdateGroupDescriptionsInput(BaseModel):
    groups: List["GroupDescriptionInput"]
    mode: BulkUpdateIdMode


class BulkUpdateIds(BaseModel):
    ids: Optional[List[str]] = None
    mode: BulkUpdateIdMode


class BulkUpdateStrings(BaseModel):
    values: Optional[List[str]] = None
    mode: BulkUpdateIdMode


class CircumcisionCriterionInput(BaseModel):
    value: Optional[List[CircumisedEnum]] = None
    modifier: CriterionModifier


class CleanGeneratedInput(BaseModel):
    blob_files: Optional[bool] = Field(alias="blobFiles", default=None)
    sprites: Optional[bool] = None
    screenshots: Optional[bool] = None
    transcodes: Optional[bool] = None
    markers: Optional[bool] = None
    image_thumbnails: Optional[bool] = Field(alias="imageThumbnails", default=None)
    dry_run: Optional[bool] = Field(alias="dryRun", default=None)


class CleanMetadataInput(BaseModel):
    paths: Optional[List[str]] = None
    dry_run: bool = Field(alias="dryRun")


class ConfigDLNAInput(BaseModel):
    server_name: Optional[str] = Field(alias="serverName", default=None)
    enabled: Optional[bool] = None
    port: Optional[int] = None
    whitelisted_i_ps: Optional[List[str]] = Field(alias="whitelistedIPs", default=None)
    interfaces: Optional[List[str]] = None
    video_sort_order: Optional[str] = Field(alias="videoSortOrder", default=None)


class ConfigDefaultSettingsInput(BaseModel):
    scan: Optional["ScanMetadataInput"] = None
    identify: Optional["IdentifyMetadataInput"] = None
    auto_tag: Optional["AutoTagMetadataInput"] = Field(alias="autoTag", default=None)
    generate: Optional["GenerateMetadataInput"] = None
    delete_file: Optional[bool] = Field(alias="deleteFile", default=None)
    delete_generated: Optional[bool] = Field(alias="deleteGenerated", default=None)


class ConfigDisableDropdownCreateInput(BaseModel):
    performer: Optional[bool] = None
    tag: Optional[bool] = None
    studio: Optional[bool] = None
    movie: Optional[bool] = None


class ConfigGeneralInput(BaseModel):
    stashes: Optional[List["StashConfigInput"]] = None
    database_path: Optional[str] = Field(alias="databasePath", default=None)
    backup_directory_path: Optional[str] = Field(
        alias="backupDirectoryPath", default=None
    )
    generated_path: Optional[str] = Field(alias="generatedPath", default=None)
    metadata_path: Optional[str] = Field(alias="metadataPath", default=None)
    scrapers_path: Optional[str] = Field(alias="scrapersPath", default=None)
    plugins_path: Optional[str] = Field(alias="pluginsPath", default=None)
    cache_path: Optional[str] = Field(alias="cachePath", default=None)
    blobs_path: Optional[str] = Field(alias="blobsPath", default=None)
    blobs_storage: Optional[BlobsStorageType] = Field(
        alias="blobsStorage", default=None
    )
    ffmpeg_path: Optional[str] = Field(alias="ffmpegPath", default=None)
    ffprobe_path: Optional[str] = Field(alias="ffprobePath", default=None)
    calculate_md_5: Optional[bool] = Field(alias="calculateMD5", default=None)
    video_file_naming_algorithm: Optional[HashAlgorithm] = Field(
        alias="videoFileNamingAlgorithm", default=None
    )
    parallel_tasks: Optional[int] = Field(alias="parallelTasks", default=None)
    preview_audio: Optional[bool] = Field(alias="previewAudio", default=None)
    preview_segments: Optional[int] = Field(alias="previewSegments", default=None)
    preview_segment_duration: Optional[float] = Field(
        alias="previewSegmentDuration", default=None
    )
    preview_exclude_start: Optional[str] = Field(
        alias="previewExcludeStart", default=None
    )
    preview_exclude_end: Optional[str] = Field(alias="previewExcludeEnd", default=None)
    preview_preset: Optional[PreviewPreset] = Field(alias="previewPreset", default=None)
    transcode_hardware_acceleration: Optional[bool] = Field(
        alias="transcodeHardwareAcceleration", default=None
    )
    max_transcode_size: Optional[StreamingResolutionEnum] = Field(
        alias="maxTranscodeSize", default=None
    )
    max_streaming_transcode_size: Optional[StreamingResolutionEnum] = Field(
        alias="maxStreamingTranscodeSize", default=None
    )
    transcode_input_args: Optional[List[str]] = Field(
        alias="transcodeInputArgs", default=None
    )
    transcode_output_args: Optional[List[str]] = Field(
        alias="transcodeOutputArgs", default=None
    )
    live_transcode_input_args: Optional[List[str]] = Field(
        alias="liveTranscodeInputArgs", default=None
    )
    live_transcode_output_args: Optional[List[str]] = Field(
        alias="liveTranscodeOutputArgs", default=None
    )
    draw_funscript_heatmap_range: Optional[bool] = Field(
        alias="drawFunscriptHeatmapRange", default=None
    )
    write_image_thumbnails: Optional[bool] = Field(
        alias="writeImageThumbnails", default=None
    )
    create_image_clips_from_videos: Optional[bool] = Field(
        alias="createImageClipsFromVideos", default=None
    )
    username: Optional[str] = None
    password: Optional[str] = None
    max_session_age: Optional[int] = Field(alias="maxSessionAge", default=None)
    log_file: Optional[str] = Field(alias="logFile", default=None)
    log_out: Optional[bool] = Field(alias="logOut", default=None)
    log_level: Optional[str] = Field(alias="logLevel", default=None)
    log_access: Optional[bool] = Field(alias="logAccess", default=None)
    create_galleries_from_folders: Optional[bool] = Field(
        alias="createGalleriesFromFolders", default=None
    )
    gallery_cover_regex: Optional[str] = Field(alias="galleryCoverRegex", default=None)
    video_extensions: Optional[List[str]] = Field(alias="videoExtensions", default=None)
    image_extensions: Optional[List[str]] = Field(alias="imageExtensions", default=None)
    gallery_extensions: Optional[List[str]] = Field(
        alias="galleryExtensions", default=None
    )
    excludes: Optional[List[str]] = None
    image_excludes: Optional[List[str]] = Field(alias="imageExcludes", default=None)
    custom_performer_image_location: Optional[str] = Field(
        alias="customPerformerImageLocation", default=None
    )
    stash_boxes: Optional[List["StashBoxInput"]] = Field(
        alias="stashBoxes", default=None
    )
    python_path: Optional[str] = Field(alias="pythonPath", default=None)
    scraper_package_sources: Optional[List["PackageSourceInput"]] = Field(
        alias="scraperPackageSources", default=None
    )
    plugin_package_sources: Optional[List["PackageSourceInput"]] = Field(
        alias="pluginPackageSources", default=None
    )


class ConfigImageLightboxInput(BaseModel):
    slideshow_delay: Optional[int] = Field(alias="slideshowDelay", default=None)
    display_mode: Optional[ImageLightboxDisplayMode] = Field(
        alias="displayMode", default=None
    )
    scale_up: Optional[bool] = Field(alias="scaleUp", default=None)
    reset_zoom_on_nav: Optional[bool] = Field(alias="resetZoomOnNav", default=None)
    scroll_mode: Optional[ImageLightboxScrollMode] = Field(
        alias="scrollMode", default=None
    )
    scroll_attempts_before_change: Optional[int] = Field(
        alias="scrollAttemptsBeforeChange", default=None
    )


class ConfigInterfaceInput(BaseModel):
    menu_items: Optional[List[str]] = Field(alias="menuItems", default=None)
    sound_on_preview: Optional[bool] = Field(alias="soundOnPreview", default=None)
    wall_show_title: Optional[bool] = Field(alias="wallShowTitle", default=None)
    wall_playback: Optional[str] = Field(alias="wallPlayback", default=None)
    show_scrubber: Optional[bool] = Field(alias="showScrubber", default=None)
    maximum_loop_duration: Optional[int] = Field(
        alias="maximumLoopDuration", default=None
    )
    autostart_video: Optional[bool] = Field(alias="autostartVideo", default=None)
    autostart_video_on_play_selected: Optional[bool] = Field(
        alias="autostartVideoOnPlaySelected", default=None
    )
    continue_playlist_default: Optional[bool] = Field(
        alias="continuePlaylistDefault", default=None
    )
    show_studio_as_text: Optional[bool] = Field(alias="showStudioAsText", default=None)
    css: Optional[str] = None
    css_enabled: Optional[bool] = Field(alias="cssEnabled", default=None)
    javascript: Optional[str] = None
    javascript_enabled: Optional[bool] = Field(alias="javascriptEnabled", default=None)
    custom_locales: Optional[str] = Field(alias="customLocales", default=None)
    custom_locales_enabled: Optional[bool] = Field(
        alias="customLocalesEnabled", default=None
    )
    language: Optional[str] = None
    image_lightbox: Optional["ConfigImageLightboxInput"] = Field(
        alias="imageLightbox", default=None
    )
    disable_dropdown_create: Optional["ConfigDisableDropdownCreateInput"] = Field(
        alias="disableDropdownCreate", default=None
    )
    handy_key: Optional[str] = Field(alias="handyKey", default=None)
    funscript_offset: Optional[int] = Field(alias="funscriptOffset", default=None)
    use_stash_hosted_funscript: Optional[bool] = Field(
        alias="useStashHostedFunscript", default=None
    )
    no_browser: Optional[bool] = Field(alias="noBrowser", default=None)
    notifications_enabled: Optional[bool] = Field(
        alias="notificationsEnabled", default=None
    )


class ConfigScrapingInput(BaseModel):
    scraper_user_agent: Optional[str] = Field(alias="scraperUserAgent", default=None)
    scraper_cdp_path: Optional[str] = Field(alias="scraperCDPPath", default=None)
    scraper_cert_check: Optional[bool] = Field(alias="scraperCertCheck", default=None)
    exclude_tag_patterns: Optional[List[str]] = Field(
        alias="excludeTagPatterns", default=None
    )


class CustomFieldCriterionInput(BaseModel):
    field: str
    value: Optional[List[Any]] = None
    modifier: CriterionModifier


class CustomFieldsInput(BaseModel):
    full: Optional[Any] = None
    partial: Optional[Any] = None


class DateCriterionInput(BaseModel):
    value: str
    value_2: Optional[str] = Field(alias="value2", default=None)
    modifier: CriterionModifier


class DestroyFilterInput(BaseModel):
    id: str


class DisableDLNAInput(BaseModel):
    duration: Optional[int] = None


class EnableDLNAInput(BaseModel):
    duration: Optional[int] = None


class ExportObjectTypeInput(BaseModel):
    ids: Optional[List[str]] = None
    all: Optional[bool] = None


class ExportObjectsInput(BaseModel):
    scenes: Optional["ExportObjectTypeInput"] = None
    images: Optional["ExportObjectTypeInput"] = None
    studios: Optional["ExportObjectTypeInput"] = None
    performers: Optional["ExportObjectTypeInput"] = None
    tags: Optional["ExportObjectTypeInput"] = None
    groups: Optional["ExportObjectTypeInput"] = None
    movies: Optional["ExportObjectTypeInput"] = None
    galleries: Optional["ExportObjectTypeInput"] = None
    include_dependencies: Optional[bool] = Field(
        alias="includeDependencies", default=None
    )


class FileSetFingerprintsInput(BaseModel):
    id: str
    fingerprints: List["SetFingerprintsInput"]


class FindFilterType(BaseModel):
    q: Optional[str] = None
    page: Optional[int] = None
    per_page: Optional[int] = None
    sort: Optional[str] = None
    direction: Optional[SortDirectionEnum] = None


class FindJobInput(BaseModel):
    id: str


class FloatCriterionInput(BaseModel):
    value: float
    value_2: Optional[float] = Field(alias="value2", default=None)
    modifier: CriterionModifier


class GalleryAddInput(BaseModel):
    gallery_id: str
    image_ids: List[str]


class GalleryChapterCreateInput(BaseModel):
    gallery_id: str
    title: str
    image_index: int


class GalleryChapterUpdateInput(BaseModel):
    id: str
    gallery_id: Optional[str] = None
    title: Optional[str] = None
    image_index: Optional[int] = None


class GalleryCreateInput(BaseModel):
    title: str
    code: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    scene_ids: Optional[List[str]] = None
    studio_id: Optional[str] = None
    tag_ids: Optional[List[str]] = None
    performer_ids: Optional[List[str]] = None


class GalleryDestroyInput(BaseModel):
    ids: List[str]
    delete_file: Optional[bool] = None
    delete_generated: Optional[bool] = None


class GalleryFilterType(BaseModel):
    and_: Optional["GalleryFilterType"] = Field(alias="AND", default=None)
    or_: Optional["GalleryFilterType"] = Field(alias="OR", default=None)
    not_: Optional["GalleryFilterType"] = Field(alias="NOT", default=None)
    id: Optional["IntCriterionInput"] = None
    title: Optional["StringCriterionInput"] = None
    details: Optional["StringCriterionInput"] = None
    checksum: Optional["StringCriterionInput"] = None
    path: Optional["StringCriterionInput"] = None
    file_count: Optional["IntCriterionInput"] = None
    is_missing: Optional[str] = None
    is_zip: Optional[bool] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    average_resolution: Optional["ResolutionCriterionInput"] = None
    has_chapters: Optional[str] = None
    scenes: Optional["MultiCriterionInput"] = None
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    performer_tags: Optional["HierarchicalMultiCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    performer_count: Optional["IntCriterionInput"] = None
    performer_favorite: Optional[bool] = None
    performer_age: Optional["IntCriterionInput"] = None
    image_count: Optional["IntCriterionInput"] = None
    url: Optional["StringCriterionInput"] = None
    date: Optional["DateCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    code: Optional["StringCriterionInput"] = None
    photographer: Optional["StringCriterionInput"] = None
    scenes_filter: Optional["SceneFilterType"] = None
    images_filter: Optional["ImageFilterType"] = None
    performers_filter: Optional["PerformerFilterType"] = None
    studios_filter: Optional["StudioFilterType"] = None
    tags_filter: Optional["TagFilterType"] = None


class GalleryRemoveInput(BaseModel):
    gallery_id: str
    image_ids: List[str]


class GalleryResetCoverInput(BaseModel):
    gallery_id: str


class GallerySetCoverInput(BaseModel):
    gallery_id: str
    cover_image_id: str


class GalleryUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    id: str
    title: Optional[str] = None
    code: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    scene_ids: Optional[List[str]] = None
    studio_id: Optional[str] = None
    tag_ids: Optional[List[str]] = None
    performer_ids: Optional[List[str]] = None
    primary_file_id: Optional[str] = None


class GenderCriterionInput(BaseModel):
    value: Optional[GenderEnum] = None
    value_list: Optional[List[GenderEnum]] = None
    modifier: CriterionModifier


class GenerateAPIKeyInput(BaseModel):
    clear: Optional[bool] = None


class GenerateMetadataInput(BaseModel):
    covers: Optional[bool] = None
    sprites: Optional[bool] = None
    previews: Optional[bool] = None
    image_previews: Optional[bool] = Field(alias="imagePreviews", default=None)
    preview_options: Optional["GeneratePreviewOptionsInput"] = Field(
        alias="previewOptions", default=None
    )
    markers: Optional[bool] = None
    marker_image_previews: Optional[bool] = Field(
        alias="markerImagePreviews", default=None
    )
    marker_screenshots: Optional[bool] = Field(alias="markerScreenshots", default=None)
    transcodes: Optional[bool] = None
    force_transcodes: Optional[bool] = Field(alias="forceTranscodes", default=None)
    phashes: Optional[bool] = None
    interactive_heatmaps_speeds: Optional[bool] = Field(
        alias="interactiveHeatmapsSpeeds", default=None
    )
    image_thumbnails: Optional[bool] = Field(alias="imageThumbnails", default=None)
    clip_previews: Optional[bool] = Field(alias="clipPreviews", default=None)
    scene_i_ds: Optional[List[str]] = Field(alias="sceneIDs", default=None)
    marker_i_ds: Optional[List[str]] = Field(alias="markerIDs", default=None)
    overwrite: Optional[bool] = None


class GeneratePreviewOptionsInput(BaseModel):
    preview_segments: Optional[int] = Field(alias="previewSegments", default=None)
    preview_segment_duration: Optional[float] = Field(
        alias="previewSegmentDuration", default=None
    )
    preview_exclude_start: Optional[str] = Field(
        alias="previewExcludeStart", default=None
    )
    preview_exclude_end: Optional[str] = Field(alias="previewExcludeEnd", default=None)
    preview_preset: Optional[PreviewPreset] = Field(alias="previewPreset", default=None)


class GroupCreateInput(BaseModel):
    name: str
    aliases: Optional[str] = None
    duration: Optional[int] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    synopsis: Optional[str] = None
    urls: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    containing_groups: Optional[List["GroupDescriptionInput"]] = None
    sub_groups: Optional[List["GroupDescriptionInput"]] = None
    front_image: Optional[str] = None
    back_image: Optional[str] = None


class GroupDescriptionInput(BaseModel):
    group_id: str
    description: Optional[str] = None


class GroupDestroyInput(BaseModel):
    id: str


class GroupFilterType(BaseModel):
    and_: Optional["GroupFilterType"] = Field(alias="AND", default=None)
    or_: Optional["GroupFilterType"] = Field(alias="OR", default=None)
    not_: Optional["GroupFilterType"] = Field(alias="NOT", default=None)
    name: Optional["StringCriterionInput"] = None
    director: Optional["StringCriterionInput"] = None
    synopsis: Optional["StringCriterionInput"] = None
    duration: Optional["IntCriterionInput"] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    is_missing: Optional[str] = None
    url: Optional["StringCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    date: Optional["DateCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    containing_groups: Optional["HierarchicalMultiCriterionInput"] = None
    sub_groups: Optional["HierarchicalMultiCriterionInput"] = None
    containing_group_count: Optional["IntCriterionInput"] = None
    sub_group_count: Optional["IntCriterionInput"] = None
    scenes_filter: Optional["SceneFilterType"] = None
    studios_filter: Optional["StudioFilterType"] = None


class GroupSubGroupAddInput(BaseModel):
    containing_group_id: str
    sub_groups: List["GroupDescriptionInput"]
    insert_index: Optional[int] = None


class GroupSubGroupRemoveInput(BaseModel):
    containing_group_id: str
    sub_group_ids: List[str]


class GroupUpdateInput(BaseModel):
    id: str
    name: Optional[str] = None
    aliases: Optional[str] = None
    duration: Optional[int] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    synopsis: Optional[str] = None
    urls: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    containing_groups: Optional[List["GroupDescriptionInput"]] = None
    sub_groups: Optional[List["GroupDescriptionInput"]] = None
    front_image: Optional[str] = None
    back_image: Optional[str] = None


class HierarchicalMultiCriterionInput(BaseModel):
    value: Optional[List[str]] = None
    modifier: CriterionModifier
    depth: Optional[int] = None
    excludes: Optional[List[str]] = None


class IdentifyFieldOptionsInput(BaseModel):
    field: str
    strategy: IdentifyFieldStrategy
    create_missing: Optional[bool] = Field(alias="createMissing", default=None)


class IdentifyMetadataInput(BaseModel):
    sources: List["IdentifySourceInput"]
    options: Optional["IdentifyMetadataOptionsInput"] = None
    scene_i_ds: Optional[List[str]] = Field(alias="sceneIDs", default=None)
    paths: Optional[List[str]] = None


class IdentifyMetadataOptionsInput(BaseModel):
    field_options: Optional[List["IdentifyFieldOptionsInput"]] = Field(
        alias="fieldOptions", default=None
    )
    set_cover_image: Optional[bool] = Field(alias="setCoverImage", default=None)
    set_organized: Optional[bool] = Field(alias="setOrganized", default=None)
    include_male_performers: Optional[bool] = Field(
        alias="includeMalePerformers", default=None
    )
    skip_multiple_matches: Optional[bool] = Field(
        alias="skipMultipleMatches", default=None
    )
    skip_multiple_match_tag: Optional[str] = Field(
        alias="skipMultipleMatchTag", default=None
    )
    skip_single_name_performers: Optional[bool] = Field(
        alias="skipSingleNamePerformers", default=None
    )
    skip_single_name_performer_tag: Optional[str] = Field(
        alias="skipSingleNamePerformerTag", default=None
    )


class IdentifySourceInput(BaseModel):
    source: "ScraperSourceInput"
    options: Optional["IdentifyMetadataOptionsInput"] = None


class ImageDestroyInput(BaseModel):
    id: str
    delete_file: Optional[bool] = None
    delete_generated: Optional[bool] = None


class ImageFilterType(BaseModel):
    and_: Optional["ImageFilterType"] = Field(alias="AND", default=None)
    or_: Optional["ImageFilterType"] = Field(alias="OR", default=None)
    not_: Optional["ImageFilterType"] = Field(alias="NOT", default=None)
    title: Optional["StringCriterionInput"] = None
    details: Optional["StringCriterionInput"] = None
    id: Optional["IntCriterionInput"] = None
    checksum: Optional["StringCriterionInput"] = None
    path: Optional["StringCriterionInput"] = None
    file_count: Optional["IntCriterionInput"] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    date: Optional["DateCriterionInput"] = None
    url: Optional["StringCriterionInput"] = None
    organized: Optional[bool] = None
    o_counter: Optional["IntCriterionInput"] = None
    resolution: Optional["ResolutionCriterionInput"] = None
    orientation: Optional["OrientationCriterionInput"] = None
    is_missing: Optional[str] = None
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    performer_tags: Optional["HierarchicalMultiCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    performer_count: Optional["IntCriterionInput"] = None
    performer_favorite: Optional[bool] = None
    performer_age: Optional["IntCriterionInput"] = None
    galleries: Optional["MultiCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    code: Optional["StringCriterionInput"] = None
    photographer: Optional["StringCriterionInput"] = None
    galleries_filter: Optional["GalleryFilterType"] = None
    performers_filter: Optional["PerformerFilterType"] = None
    studios_filter: Optional["StudioFilterType"] = None
    tags_filter: Optional["TagFilterType"] = None


class ImageUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    id: str
    title: Optional[str] = None
    code: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    studio_id: Optional[str] = None
    performer_ids: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    gallery_ids: Optional[List[str]] = None
    primary_file_id: Optional[str] = None


class ImagesDestroyInput(BaseModel):
    ids: List[str]
    delete_file: Optional[bool] = None
    delete_generated: Optional[bool] = None


class ImportObjectsInput(BaseModel):
    file: Upload
    duplicate_behaviour: ImportDuplicateEnum = Field(alias="duplicateBehaviour")
    missing_ref_behaviour: ImportMissingRefEnum = Field(alias="missingRefBehaviour")


class IntCriterionInput(BaseModel):
    value: int
    value_2: Optional[int] = Field(alias="value2", default=None)
    modifier: CriterionModifier


class MigrateBlobsInput(BaseModel):
    delete_old: Optional[bool] = Field(alias="deleteOld", default=None)


class MigrateInput(BaseModel):
    backup_path: str = Field(alias="backupPath")


class MigrateSceneScreenshotsInput(BaseModel):
    delete_files: Optional[bool] = Field(alias="deleteFiles", default=None)
    overwrite_existing: Optional[bool] = Field(alias="overwriteExisting", default=None)


class MoveFilesInput(BaseModel):
    ids: List[str]
    destination_folder: Optional[str] = None
    destination_folder_id: Optional[str] = None
    destination_basename: Optional[str] = None


class MovieCreateInput(BaseModel):
    name: str
    aliases: Optional[str] = None
    duration: Optional[int] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    synopsis: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    front_image: Optional[str] = None
    back_image: Optional[str] = None


class MovieDestroyInput(BaseModel):
    id: str


class MovieFilterType(BaseModel):
    and_: Optional["MovieFilterType"] = Field(alias="AND", default=None)
    or_: Optional["MovieFilterType"] = Field(alias="OR", default=None)
    not_: Optional["MovieFilterType"] = Field(alias="NOT", default=None)
    name: Optional["StringCriterionInput"] = None
    director: Optional["StringCriterionInput"] = None
    synopsis: Optional["StringCriterionInput"] = None
    duration: Optional["IntCriterionInput"] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    is_missing: Optional[str] = None
    url: Optional["StringCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    date: Optional["DateCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    scenes_filter: Optional["SceneFilterType"] = None
    studios_filter: Optional["StudioFilterType"] = None


class MovieUpdateInput(BaseModel):
    id: str
    name: Optional[str] = None
    aliases: Optional[str] = None
    duration: Optional[int] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    studio_id: Optional[str] = None
    director: Optional[str] = None
    synopsis: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    front_image: Optional[str] = None
    back_image: Optional[str] = None


class MultiCriterionInput(BaseModel):
    value: Optional[List[str]] = None
    modifier: CriterionModifier
    excludes: Optional[List[str]] = None


class OrientationCriterionInput(BaseModel):
    value: List[OrientationEnum]


class PHashDuplicationCriterionInput(BaseModel):
    duplicated: Optional[bool] = None
    distance: Optional[int] = None


class PackageSourceInput(BaseModel):
    name: Optional[str] = None
    url: str
    local_path: Optional[str] = None


class PackageSpecInput(BaseModel):
    id: str
    source_url: str = Field(alias="sourceURL")


class PerformerCreateInput(BaseModel):
    name: str
    disambiguation: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    gender: Optional[GenderEnum] = None
    birthdate: Optional[str] = None
    ethnicity: Optional[str] = None
    country: Optional[str] = None
    eye_color: Optional[str] = None
    height_cm: Optional[int] = None
    measurements: Optional[str] = None
    fake_tits: Optional[str] = None
    penis_length: Optional[float] = None
    circumcised: Optional[CircumisedEnum] = None
    career_length: Optional[str] = None
    tattoos: Optional[str] = None
    piercings: Optional[str] = None
    alias_list: Optional[List[str]] = None
    twitter: Optional[str] = None
    instagram: Optional[str] = None
    favorite: Optional[bool] = None
    tag_ids: Optional[List[str]] = None
    image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    details: Optional[str] = None
    death_date: Optional[str] = None
    hair_color: Optional[str] = None
    weight: Optional[int] = None
    ignore_auto_tag: Optional[bool] = None
    custom_fields: Optional[Any] = None


class PerformerDestroyInput(BaseModel):
    id: str


class PerformerFilterType(BaseModel):
    and_: Optional["PerformerFilterType"] = Field(alias="AND", default=None)
    or_: Optional["PerformerFilterType"] = Field(alias="OR", default=None)
    not_: Optional["PerformerFilterType"] = Field(alias="NOT", default=None)
    name: Optional["StringCriterionInput"] = None
    disambiguation: Optional["StringCriterionInput"] = None
    details: Optional["StringCriterionInput"] = None
    filter_favorites: Optional[bool] = None
    birth_year: Optional["IntCriterionInput"] = None
    age: Optional["IntCriterionInput"] = None
    ethnicity: Optional["StringCriterionInput"] = None
    country: Optional["StringCriterionInput"] = None
    eye_color: Optional["StringCriterionInput"] = None
    height_cm: Optional["IntCriterionInput"] = None
    measurements: Optional["StringCriterionInput"] = None
    fake_tits: Optional["StringCriterionInput"] = None
    penis_length: Optional["FloatCriterionInput"] = None
    circumcised: Optional["CircumcisionCriterionInput"] = None
    career_length: Optional["StringCriterionInput"] = None
    tattoos: Optional["StringCriterionInput"] = None
    piercings: Optional["StringCriterionInput"] = None
    aliases: Optional["StringCriterionInput"] = None
    gender: Optional["GenderCriterionInput"] = None
    is_missing: Optional[str] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    scene_count: Optional["IntCriterionInput"] = None
    image_count: Optional["IntCriterionInput"] = None
    gallery_count: Optional["IntCriterionInput"] = None
    play_count: Optional["IntCriterionInput"] = None
    o_counter: Optional["IntCriterionInput"] = None
    stash_id_endpoint: Optional["StashIDCriterionInput"] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    url: Optional["StringCriterionInput"] = None
    hair_color: Optional["StringCriterionInput"] = None
    weight: Optional["IntCriterionInput"] = None
    death_year: Optional["IntCriterionInput"] = None
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    ignore_auto_tag: Optional[bool] = None
    birthdate: Optional["DateCriterionInput"] = None
    death_date: Optional["DateCriterionInput"] = None
    scenes_filter: Optional["SceneFilterType"] = None
    images_filter: Optional["ImageFilterType"] = None
    galleries_filter: Optional["GalleryFilterType"] = None
    tags_filter: Optional["TagFilterType"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    custom_fields: Optional[List["CustomFieldCriterionInput"]] = None


class PerformerUpdateInput(BaseModel):
    id: str
    name: Optional[str] = None
    disambiguation: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    gender: Optional[GenderEnum] = None
    birthdate: Optional[str] = None
    ethnicity: Optional[str] = None
    country: Optional[str] = None
    eye_color: Optional[str] = None
    height_cm: Optional[int] = None
    measurements: Optional[str] = None
    fake_tits: Optional[str] = None
    penis_length: Optional[float] = None
    circumcised: Optional[CircumisedEnum] = None
    career_length: Optional[str] = None
    tattoos: Optional[str] = None
    piercings: Optional[str] = None
    alias_list: Optional[List[str]] = None
    twitter: Optional[str] = None
    instagram: Optional[str] = None
    favorite: Optional[bool] = None
    tag_ids: Optional[List[str]] = None
    image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    details: Optional[str] = None
    death_date: Optional[str] = None
    hair_color: Optional[str] = None
    weight: Optional[int] = None
    ignore_auto_tag: Optional[bool] = None
    custom_fields: Optional["CustomFieldsInput"] = None


class PhashDistanceCriterionInput(BaseModel):
    value: str
    modifier: CriterionModifier
    distance: Optional[int] = None


class PluginArgInput(BaseModel):
    key: str
    value: Optional["PluginValueInput"] = None


class PluginValueInput(BaseModel):
    str: Optional[str] = None
    i: Optional[int] = None
    b: Optional[bool] = None
    f: Optional[float] = None
    o: Optional[List["PluginArgInput"]] = None
    a: Optional[List["PluginValueInput"]] = None


class RemoveTempDLNAIPInput(BaseModel):
    address: str


class ReorderSubGroupsInput(BaseModel):
    group_id: str
    sub_group_ids: List[str]
    insert_at_id: str
    insert_after: Optional[bool] = None


class ResolutionCriterionInput(BaseModel):
    value: ResolutionEnum
    modifier: CriterionModifier


class SaveFilterInput(BaseModel):
    id: Optional[str] = None
    mode: FilterMode
    name: str
    find_filter: Optional["FindFilterType"] = None
    object_filter: Optional[Any] = None
    ui_options: Optional[Any] = None


class ScanMetaDataFilterInput(BaseModel):
    min_mod_time: Optional[Any] = Field(alias="minModTime", default=None)


class ScanMetadataInput(BaseModel):
    paths: Optional[List[str]] = None
    rescan: Optional[bool] = None
    scan_generate_covers: Optional[bool] = Field(
        alias="scanGenerateCovers", default=None
    )
    scan_generate_previews: Optional[bool] = Field(
        alias="scanGeneratePreviews", default=None
    )
    scan_generate_image_previews: Optional[bool] = Field(
        alias="scanGenerateImagePreviews", default=None
    )
    scan_generate_sprites: Optional[bool] = Field(
        alias="scanGenerateSprites", default=None
    )
    scan_generate_phashes: Optional[bool] = Field(
        alias="scanGeneratePhashes", default=None
    )
    scan_generate_thumbnails: Optional[bool] = Field(
        alias="scanGenerateThumbnails", default=None
    )
    scan_generate_clip_previews: Optional[bool] = Field(
        alias="scanGenerateClipPreviews", default=None
    )
    filter: Optional["ScanMetaDataFilterInput"] = None


class SceneCreateInput(BaseModel):
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    director: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    studio_id: Optional[str] = None
    gallery_ids: Optional[List[str]] = None
    performer_ids: Optional[List[str]] = None
    groups: Optional[List["SceneGroupInput"]] = None
    movies: Optional[List["SceneMovieInput"]] = None
    tag_ids: Optional[List[str]] = None
    cover_image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    file_ids: Optional[List[str]] = None


class SceneDestroyInput(BaseModel):
    id: str
    delete_file: Optional[bool] = None
    delete_generated: Optional[bool] = None


class SceneFilterType(BaseModel):
    and_: Optional["SceneFilterType"] = Field(alias="AND", default=None)
    or_: Optional["SceneFilterType"] = Field(alias="OR", default=None)
    not_: Optional["SceneFilterType"] = Field(alias="NOT", default=None)
    id: Optional["IntCriterionInput"] = None
    title: Optional["StringCriterionInput"] = None
    code: Optional["StringCriterionInput"] = None
    details: Optional["StringCriterionInput"] = None
    director: Optional["StringCriterionInput"] = None
    oshash: Optional["StringCriterionInput"] = None
    checksum: Optional["StringCriterionInput"] = None
    phash: Optional["StringCriterionInput"] = None
    phash_distance: Optional["PhashDistanceCriterionInput"] = None
    path: Optional["StringCriterionInput"] = None
    file_count: Optional["IntCriterionInput"] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    organized: Optional[bool] = None
    o_counter: Optional["IntCriterionInput"] = None
    duplicated: Optional["PHashDuplicationCriterionInput"] = None
    resolution: Optional["ResolutionCriterionInput"] = None
    orientation: Optional["OrientationCriterionInput"] = None
    framerate: Optional["IntCriterionInput"] = None
    bitrate: Optional["IntCriterionInput"] = None
    video_codec: Optional["StringCriterionInput"] = None
    audio_codec: Optional["StringCriterionInput"] = None
    duration: Optional["IntCriterionInput"] = None
    has_markers: Optional[str] = None
    is_missing: Optional[str] = None
    studios: Optional["HierarchicalMultiCriterionInput"] = None
    movies: Optional["MultiCriterionInput"] = None
    groups: Optional["HierarchicalMultiCriterionInput"] = None
    galleries: Optional["MultiCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    performer_tags: Optional["HierarchicalMultiCriterionInput"] = None
    performer_favorite: Optional[bool] = None
    performer_age: Optional["IntCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    performer_count: Optional["IntCriterionInput"] = None
    stash_id_endpoint: Optional["StashIDCriterionInput"] = None
    url: Optional["StringCriterionInput"] = None
    interactive: Optional[bool] = None
    interactive_speed: Optional["IntCriterionInput"] = None
    captions: Optional["StringCriterionInput"] = None
    resume_time: Optional["IntCriterionInput"] = None
    play_count: Optional["IntCriterionInput"] = None
    play_duration: Optional["IntCriterionInput"] = None
    last_played_at: Optional["TimestampCriterionInput"] = None
    date: Optional["DateCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    galleries_filter: Optional["GalleryFilterType"] = None
    performers_filter: Optional["PerformerFilterType"] = None
    studios_filter: Optional["StudioFilterType"] = None
    tags_filter: Optional["TagFilterType"] = None
    movies_filter: Optional["MovieFilterType"] = None
    groups_filter: Optional["GroupFilterType"] = None
    markers_filter: Optional["SceneMarkerFilterType"] = None


class SceneGroupInput(BaseModel):
    group_id: str
    scene_index: Optional[int] = None


class SceneHashInput(BaseModel):
    checksum: Optional[str] = None
    oshash: Optional[str] = None


class SceneMarkerCreateInput(BaseModel):
    title: str
    seconds: float
    end_seconds: Optional[float] = None
    scene_id: str
    primary_tag_id: str
    tag_ids: Optional[List[str]] = None


class SceneMarkerFilterType(BaseModel):
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    scene_tags: Optional["HierarchicalMultiCriterionInput"] = None
    performers: Optional["MultiCriterionInput"] = None
    scenes: Optional["MultiCriterionInput"] = None
    duration: Optional["FloatCriterionInput"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None
    scene_date: Optional["DateCriterionInput"] = None
    scene_created_at: Optional["TimestampCriterionInput"] = None
    scene_updated_at: Optional["TimestampCriterionInput"] = None
    scene_filter: Optional["SceneFilterType"] = None


class SceneMarkerUpdateInput(BaseModel):
    id: str
    title: Optional[str] = None
    seconds: Optional[float] = None
    end_seconds: Optional[float] = None
    scene_id: Optional[str] = None
    primary_tag_id: Optional[str] = None
    tag_ids: Optional[List[str]] = None


class SceneMergeInput(BaseModel):
    source: List[str]
    destination: str
    values: Optional["SceneUpdateInput"] = None
    play_history: Optional[bool] = None
    o_history: Optional[bool] = None


class SceneMovieInput(BaseModel):
    movie_id: str
    scene_index: Optional[int] = None


class SceneParserInput(BaseModel):
    ignore_words: Optional[List[str]] = Field(alias="ignoreWords", default=None)
    whitespace_characters: Optional[str] = Field(
        alias="whitespaceCharacters", default=None
    )
    capitalize_title: Optional[bool] = Field(alias="capitalizeTitle", default=None)
    ignore_organized: Optional[bool] = Field(alias="ignoreOrganized", default=None)


class SceneUpdateInput(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId", default=None)
    id: str
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    director: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    o_counter: Optional[int] = None
    organized: Optional[bool] = None
    studio_id: Optional[str] = None
    gallery_ids: Optional[List[str]] = None
    performer_ids: Optional[List[str]] = None
    groups: Optional[List["SceneGroupInput"]] = None
    movies: Optional[List["SceneMovieInput"]] = None
    tag_ids: Optional[List[str]] = None
    cover_image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    resume_time: Optional[float] = None
    play_duration: Optional[float] = None
    play_count: Optional[int] = None
    primary_file_id: Optional[str] = None


class ScenesDestroyInput(BaseModel):
    ids: List[str]
    delete_file: Optional[bool] = None
    delete_generated: Optional[bool] = None


class ScrapeMultiPerformersInput(BaseModel):
    performer_ids: Optional[List[str]] = None


class ScrapeMultiScenesInput(BaseModel):
    scene_ids: Optional[List[str]] = None


class ScrapeSingleGalleryInput(BaseModel):
    query: Optional[str] = None
    gallery_id: Optional[str] = None
    gallery_input: Optional["ScrapedGalleryInput"] = None


class ScrapeSingleGroupInput(BaseModel):
    query: Optional[str] = None
    group_id: Optional[str] = None
    group_input: Optional["ScrapedGroupInput"] = None


class ScrapeSingleImageInput(BaseModel):
    query: Optional[str] = None
    image_id: Optional[str] = None
    image_input: Optional["ScrapedImageInput"] = None


class ScrapeSingleMovieInput(BaseModel):
    query: Optional[str] = None
    movie_id: Optional[str] = None
    movie_input: Optional["ScrapedMovieInput"] = None


class ScrapeSinglePerformerInput(BaseModel):
    query: Optional[str] = None
    performer_id: Optional[str] = None
    performer_input: Optional["ScrapedPerformerInput"] = None


class ScrapeSingleSceneInput(BaseModel):
    query: Optional[str] = None
    scene_id: Optional[str] = None
    scene_input: Optional["ScrapedSceneInput"] = None


class ScrapeSingleStudioInput(BaseModel):
    query: Optional[str] = None


class ScrapedGalleryInput(BaseModel):
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    photographer: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None


class ScrapedGroupInput(BaseModel):
    name: Optional[str] = None
    aliases: Optional[str] = None
    duration: Optional[str] = None
    date: Optional[str] = None
    rating: Optional[str] = None
    director: Optional[str] = None
    urls: Optional[List[str]] = None
    synopsis: Optional[str] = None


class ScrapedImageInput(BaseModel):
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None


class ScrapedMovieInput(BaseModel):
    name: Optional[str] = None
    aliases: Optional[str] = None
    duration: Optional[str] = None
    date: Optional[str] = None
    rating: Optional[str] = None
    director: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    synopsis: Optional[str] = None


class ScrapedPerformerInput(BaseModel):
    stored_id: Optional[str] = None
    name: Optional[str] = None
    disambiguation: Optional[str] = None
    gender: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    twitter: Optional[str] = None
    instagram: Optional[str] = None
    birthdate: Optional[str] = None
    ethnicity: Optional[str] = None
    country: Optional[str] = None
    eye_color: Optional[str] = None
    height: Optional[str] = None
    measurements: Optional[str] = None
    fake_tits: Optional[str] = None
    penis_length: Optional[str] = None
    circumcised: Optional[str] = None
    career_length: Optional[str] = None
    tattoos: Optional[str] = None
    piercings: Optional[str] = None
    aliases: Optional[str] = None
    details: Optional[str] = None
    death_date: Optional[str] = None
    hair_color: Optional[str] = None
    weight: Optional[str] = None
    remote_site_id: Optional[str] = None


class ScrapedSceneInput(BaseModel):
    title: Optional[str] = None
    code: Optional[str] = None
    details: Optional[str] = None
    director: Optional[str] = None
    url: Optional[str] = None
    urls: Optional[List[str]] = None
    date: Optional[str] = None
    remote_site_id: Optional[str] = None


class ScraperSourceInput(BaseModel):
    stash_box_index: Optional[int] = None
    stash_box_endpoint: Optional[str] = None
    scraper_id: Optional[str] = None


class SetDefaultFilterInput(BaseModel):
    mode: FilterMode
    find_filter: Optional["FindFilterType"] = None
    object_filter: Optional[Any] = None
    ui_options: Optional[Any] = None


class SetFingerprintsInput(BaseModel):
    type: str
    value: Optional[str] = None


class SetupInput(BaseModel):
    config_location: str = Field(alias="configLocation")
    stashes: List["StashConfigInput"]
    database_file: str = Field(alias="databaseFile")
    generated_location: str = Field(alias="generatedLocation")
    cache_location: str = Field(alias="cacheLocation")
    store_blobs_in_database: bool = Field(alias="storeBlobsInDatabase")
    blobs_location: str = Field(alias="blobsLocation")


class StashBoxBatchTagInput(BaseModel):
    endpoint: Optional[int] = None
    stash_box_endpoint: Optional[str] = None
    exclude_fields: Optional[List[str]] = None
    refresh: bool
    create_parent: bool = Field(alias="createParent")
    ids: Optional[List[str]] = None
    names: Optional[List[str]] = None
    performer_ids: Optional[List[str]] = None
    performer_names: Optional[List[str]] = None


class StashBoxDraftSubmissionInput(BaseModel):
    id: str
    stash_box_index: Optional[int] = None
    stash_box_endpoint: Optional[str] = None


class StashBoxFingerprintSubmissionInput(BaseModel):
    scene_ids: List[str]
    stash_box_index: Optional[int] = None
    stash_box_endpoint: Optional[str] = None


class StashBoxInput(BaseModel):
    endpoint: str
    api_key: str
    name: str


class StashBoxPerformerQueryInput(BaseModel):
    stash_box_index: Optional[int] = None
    stash_box_endpoint: Optional[str] = None
    performer_ids: Optional[List[str]] = None
    q: Optional[str] = None


class StashBoxSceneQueryInput(BaseModel):
    stash_box_index: Optional[int] = None
    stash_box_endpoint: Optional[str] = None
    scene_ids: Optional[List[str]] = None
    q: Optional[str] = None


class StashConfigInput(BaseModel):
    path: str
    exclude_video: bool = Field(alias="excludeVideo")
    exclude_image: bool = Field(alias="excludeImage")


class StashIDCriterionInput(BaseModel):
    endpoint: Optional[str] = None
    stash_id: Optional[str] = None
    modifier: CriterionModifier


class StashIDInput(BaseModel):
    endpoint: str
    stash_id: str
    updated_at: Optional[Any] = None


class StringCriterionInput(BaseModel):
    value: str
    modifier: CriterionModifier


class StudioCreateInput(BaseModel):
    name: str
    url: Optional[str] = None
    parent_id: Optional[str] = None
    image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    favorite: Optional[bool] = None
    details: Optional[str] = None
    aliases: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    ignore_auto_tag: Optional[bool] = None


class StudioDestroyInput(BaseModel):
    id: str


class StudioFilterType(BaseModel):
    and_: Optional["StudioFilterType"] = Field(alias="AND", default=None)
    or_: Optional["StudioFilterType"] = Field(alias="OR", default=None)
    not_: Optional["StudioFilterType"] = Field(alias="NOT", default=None)
    name: Optional["StringCriterionInput"] = None
    details: Optional["StringCriterionInput"] = None
    parents: Optional["MultiCriterionInput"] = None
    stash_id_endpoint: Optional["StashIDCriterionInput"] = None
    tags: Optional["HierarchicalMultiCriterionInput"] = None
    is_missing: Optional[str] = None
    rating_100: Optional["IntCriterionInput"] = Field(alias="rating100", default=None)
    favorite: Optional[bool] = None
    scene_count: Optional["IntCriterionInput"] = None
    image_count: Optional["IntCriterionInput"] = None
    gallery_count: Optional["IntCriterionInput"] = None
    tag_count: Optional["IntCriterionInput"] = None
    url: Optional["StringCriterionInput"] = None
    aliases: Optional["StringCriterionInput"] = None
    child_count: Optional["IntCriterionInput"] = None
    ignore_auto_tag: Optional[bool] = None
    scenes_filter: Optional["SceneFilterType"] = None
    images_filter: Optional["ImageFilterType"] = None
    galleries_filter: Optional["GalleryFilterType"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None


class StudioUpdateInput(BaseModel):
    id: str
    name: Optional[str] = None
    url: Optional[str] = None
    parent_id: Optional[str] = None
    image: Optional[str] = None
    stash_ids: Optional[List["StashIDInput"]] = None
    rating_100: Optional[int] = Field(alias="rating100", default=None)
    favorite: Optional[bool] = None
    details: Optional[str] = None
    aliases: Optional[List[str]] = None
    tag_ids: Optional[List[str]] = None
    ignore_auto_tag: Optional[bool] = None


class TagCreateInput(BaseModel):
    name: str
    sort_name: Optional[str] = None
    description: Optional[str] = None
    aliases: Optional[List[str]] = None
    ignore_auto_tag: Optional[bool] = None
    favorite: Optional[bool] = None
    image: Optional[str] = None
    parent_ids: Optional[List[str]] = None
    child_ids: Optional[List[str]] = None


class TagDestroyInput(BaseModel):
    id: str


class TagFilterType(BaseModel):
    and_: Optional["TagFilterType"] = Field(alias="AND", default=None)
    or_: Optional["TagFilterType"] = Field(alias="OR", default=None)
    not_: Optional["TagFilterType"] = Field(alias="NOT", default=None)
    name: Optional["StringCriterionInput"] = None
    sort_name: Optional["StringCriterionInput"] = None
    aliases: Optional["StringCriterionInput"] = None
    favorite: Optional[bool] = None
    description: Optional["StringCriterionInput"] = None
    is_missing: Optional[str] = None
    scene_count: Optional["IntCriterionInput"] = None
    image_count: Optional["IntCriterionInput"] = None
    gallery_count: Optional["IntCriterionInput"] = None
    performer_count: Optional["IntCriterionInput"] = None
    studio_count: Optional["IntCriterionInput"] = None
    movie_count: Optional["IntCriterionInput"] = None
    group_count: Optional["IntCriterionInput"] = None
    marker_count: Optional["IntCriterionInput"] = None
    parents: Optional["HierarchicalMultiCriterionInput"] = None
    children: Optional["HierarchicalMultiCriterionInput"] = None
    parent_count: Optional["IntCriterionInput"] = None
    child_count: Optional["IntCriterionInput"] = None
    ignore_auto_tag: Optional[bool] = None
    scenes_filter: Optional["SceneFilterType"] = None
    images_filter: Optional["ImageFilterType"] = None
    galleries_filter: Optional["GalleryFilterType"] = None
    created_at: Optional["TimestampCriterionInput"] = None
    updated_at: Optional["TimestampCriterionInput"] = None


class TagUpdateInput(BaseModel):
    id: str
    name: Optional[str] = None
    sort_name: Optional[str] = None
    description: Optional[str] = None
    aliases: Optional[List[str]] = None
    ignore_auto_tag: Optional[bool] = None
    favorite: Optional[bool] = None
    image: Optional[str] = None
    parent_ids: Optional[List[str]] = None
    child_ids: Optional[List[str]] = None


class TagsMergeInput(BaseModel):
    source: List[str]
    destination: str


class TimestampCriterionInput(BaseModel):
    value: str
    value_2: Optional[str] = Field(alias="value2", default=None)
    modifier: CriterionModifier


BulkGalleryUpdateInput.model_rebuild()
BulkGroupUpdateInput.model_rebuild()
BulkImageUpdateInput.model_rebuild()
BulkMovieUpdateInput.model_rebuild()
BulkPerformerUpdateInput.model_rebuild()
BulkSceneUpdateInput.model_rebuild()
BulkTagUpdateInput.model_rebuild()
BulkUpdateGroupDescriptionsInput.model_rebuild()
ConfigDefaultSettingsInput.model_rebuild()
ConfigGeneralInput.model_rebuild()
ConfigInterfaceInput.model_rebuild()
ExportObjectsInput.model_rebuild()
FileSetFingerprintsInput.model_rebuild()
GalleryFilterType.model_rebuild()
GenerateMetadataInput.model_rebuild()
GroupCreateInput.model_rebuild()
GroupFilterType.model_rebuild()
GroupSubGroupAddInput.model_rebuild()
GroupUpdateInput.model_rebuild()
IdentifyMetadataInput.model_rebuild()
IdentifyMetadataOptionsInput.model_rebuild()
IdentifySourceInput.model_rebuild()
ImageFilterType.model_rebuild()
MovieFilterType.model_rebuild()
PerformerCreateInput.model_rebuild()
PerformerFilterType.model_rebuild()
PerformerUpdateInput.model_rebuild()
PluginArgInput.model_rebuild()
PluginValueInput.model_rebuild()
SaveFilterInput.model_rebuild()
ScanMetadataInput.model_rebuild()
SceneCreateInput.model_rebuild()
SceneFilterType.model_rebuild()
SceneMarkerFilterType.model_rebuild()
SceneMergeInput.model_rebuild()
SceneUpdateInput.model_rebuild()
ScrapeSingleGalleryInput.model_rebuild()
ScrapeSingleGroupInput.model_rebuild()
ScrapeSingleImageInput.model_rebuild()
ScrapeSingleMovieInput.model_rebuild()
ScrapeSinglePerformerInput.model_rebuild()
ScrapeSingleSceneInput.model_rebuild()
SetDefaultFilterInput.model_rebuild()
SetupInput.model_rebuild()
StudioCreateInput.model_rebuild()
StudioFilterType.model_rebuild()
StudioUpdateInput.model_rebuild()
TagFilterType.model_rebuild()
