# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class TagsByRegex(BaseModel):
    find_tags: "TagsByRegexFindTags" = Field(alias="findTags")


class TagsByRegexFindTags(BaseModel):
    tags: List["TagsByRegexFindTagsTags"]


class TagsByRegexFindTagsTags(BaseModel):
    id: str
    name: str


TagsByRegex.model_rebuild()
TagsByRegexFindTags.model_rebuild()
